apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-processor-7008
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-processor-7008
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
